name: use_case_generator
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  use_case: 
    path: ../use_case/ 

  build: ^2.4.1 
  source_gen: ^1.5.0
  path: ^1.9.0
  analyzer: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  source_gen_test: ^1.1.1

flutter:
  uses-material-design: true
